knpu_oauth2_client:
  clients:
    vkontakte:
      type: generic
      provider_class: App\Security\Providers\Vk\VkProvider
      client_id: '%env(OAUTH_VK_CLIENT_ID)%'
      client_secret: '%env(OAUTH_VK_CLIENT_SECRET)%'
      redirect_route: connect_vk_check
      use_state: false